//
// Created by tony on 22-4-16.
//

#ifndef POINTCLOUD_PCA_TEST_MULRANPOINTCLOUDSELECT_H
#define POINTCLOUD_PCA_TEST_MULRANPOINTCLOUDSELECT_H


class MulranPointCloudSelect {

};


#endif //POINTCLOUD_PCA_TEST_MULRANPOINTCLOUDSELECT_H
