//
// Created by tony on 22-4-23.
//

#ifndef POINTCLOUD_PCA_TEST_OXFORDPOINTCLOUDSELECT_H
#define POINTCLOUD_PCA_TEST_OXFORDPOINTCLOUDSELECT_H


class OxfordPointCloudSelect {

};


#endif //POINTCLOUD_PCA_TEST_OXFORDPOINTCLOUDSELECT_H
